# kubenetes yaml to deploy the loader
#
apiVersion: batch/v1
kind: Job
metadata:
  name: cmpt756loader
  labels:
    app: cmpt756loader
spec:
  template:
    metadata:
      labels:
        app: cmpt756loader
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      # svc-loader defined at DB service creation
      serviceAccountName: svc-loader
      containers:
      - name: loader
        imagePullPolicy: Always
        image: 'ZZ-CR-ID/ZZ-REG-ID/cmpt756loader:v1'
        env:
        - name: SVC_LOADER_TOKEN
          valueFrom:
            secretKeyRef:
              # The known name of secret/svc-loader-token
              name: svc-loader-token
              key: token
        volumeMounts:
        - name: book
          mountPath: "/data/book"
          readOnly: true
        - name: reader
          mountPath: "/data/reader"
          readOnly: true
        - name: bestseller
          mountPath: "/data/bestseller"
          readOnly: true
      volumes:
      - name: book
        configMap:
          name: book
      - name: reader
        configMap:
          name: reader
      - name: bestseller
        configMap:
          name: bestseller
      restartPolicy: Never
  backoffLimit: 0
